### ISSUE TITLE
move track

### ISSUE THREAD

**Issue by jmls** [nickp10/youtube-music-ts-api#11]
Is there a way of moving a track up or down in a playlist, apart from getting all the tracks, changing the order of a track, deleting all tracks and then adding the rearranged tracks back in ?

**Comment by nickp10** [comment]
This issue has been resolved and released under 1.5.0. View the new method documentation here:

https://github.com/nickp10/youtube-music-ts-api/blob/master/DOCUMENTATION.md#movetrackwithinplaylist
