### ISSUE TITLE
What node version is should be used for running and building this project?

### ISSUE THREAD

**Issue by FoxxMD** [nickp10/youtube-music-ts-api#28]
[`package.json`](https://github.com/nickp10/youtube-music-ts-api/blob/c9941c8b25189d75d2c02e8fd1256e1ead2611d7/package.json) does not specify the node/npm version using [`engines`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines) and the project does not include an [`.nvmrc`](https://github.com/nvm-sh/nvm#nvmrc) file -- can you specify what the minimum or required node/npm versions should be

**Comment by nickp10** [comment]
I'm using Node 18.161.
