### ISSUE TITLE
Reproducible build on 1.6.0

### ISSUE THREAD

**Issue by FoxxMD** [nickp10/youtube-music-ts-api#29]
[`exports.js`](https://www.npmjs.com/package/youtube-music-ts-api/v/1.6.0?activeTab=code) from the 1.6.0 npm package differs greatly when compared to `exports.js` built from the [1.6.0 repo commit.](https://github.com/nickp10/youtube-music-ts-api/tree/c9941c8b25189d75d2c02e8fd1256e1ead2611d7)

![diff](https://github.com/nickp10/youtube-music-ts-api/assets/4663766/d90f7fe2-4d40-437e-ab00-b6e147f2dca5)

(left is from npm, right is built from repo)

To build from repo (tested with Node 14/16/18):

* Clone the repo
* `npm install`
* `npm run prepare`

___

This might be related to #28 as I don't know what npm/node versions should be used. 

1.6.0 from npm does work for [fixing authentication for user's cookies](https://github.com/nickp10/youtube-music-ts-api/commit/8355ef45dc9a1812be4d76eff5a2dc5bf329f80d) but the version built from the repo does not. Is this due to not having correct dependency versions (due to npm/node), is there something else that should be done to reproduce the prod build, or is there work missing in the npm version that is not in the repo?

**Comment by nickp10** [comment]
exports.js is built using Node 18.16.1. You need to make sure you have no local changes and you have the version of the npm dependencies as defined in the package.json file (not any versions compatible with those versions).

**Comment by nickp10** [comment]
I have re-ran the `npm run prepare` locally and produced the same result as uploaded to npm. Closing as not an issue.
