### ISSUE TITLE
[BUG]: YouTubeMusic is not a constructor

### ISSUE THREAD

**Issue by SomeAspy** [nickp10/youtube-music-ts-api#33]
### Please describe the current behaviour of the code.

Following the example in the readme will cause a `TypeError: YouTubeMusic is not a constructor`

### Please describe the expected behaviour of the code.

This error should not occur

### What are the steps to reproduce the error?

Slightly modified code based off the readme example:
```ts
import YouTubeMusic from "youtube-music-ts-api";

import untypedConfig from "../config/config.json" assert { type: "json" };
import type { Config } from "./types/config.js";
const { YouTubeMusicCookie } = untypedConfig as Config;

const cookieStr = YouTubeMusicCookie;
const ytm = new YouTubeMusic(); // "TypeError: YouTubeMusic is not a constructor" on build
const ytma = await ytm.authenticate(cookieStr);
const playlists = await ytma.getLibraryPlaylists();
console.log(playlists);
```

### Additional Information

typescript 5.4.2 (also tested with 5.2.2)
tsx 4.7.1
youtube-music-ts-api 1.7.0
node 21.7.1 (also tested with 18.19.1)

**Comment by nickp10** [comment]
I'd be curious to see your tsconfig.json since this is working just fine for me on node 20. In particular, I think it could be this in the tsconfig.json file:

`"compilerOptions": {
        "module": "commonjs"
}`

**Comment by SomeAspy** [comment]
Sorry this took so long to get back to you on.
I set up an example repository - https://github.com/SomeAspy/ytm-ts-33
In this case I used `NodeNext` for modules (which is what I typically do), but I was also not able to get it working using `commonjs`

This is a really quick and dirty example, just run `pnpm i` and `pnpm run dev`

**Comment by nickp10** [comment]
I investigated this a little further and I think this is an issue with `tsx`. Here is the corresponding bug dealing with `tsx` and default exports:

https://github.com/privatenumber/tsx/issues/427

The simplest workaround in your setup to make this is to work is to remove the `type: "module"` from the package.json file and then make the code into an async function to avoid the await at the top-level error:

```
(async () => {
    const ytm = new YouTubeMusic(); // "TypeError: YouTubeMusic is not a constructor" on build
    const ytma = await ytm.authenticate(process.env.YOUTUBE_COOKIE);
    const playlists = await ytma.getLibraryPlaylists();
    console.log(playlists);
})();
```

**Comment by nickp10** [comment]
Also a workaround mentioned from this similar issue is to use `new YouTubeMusic.default()`.

https://github.com/zS1L3NT/ts-npm-ytmusic-api/issues/30

**Comment by SomeAspy** [comment]
Ah, my bad I should have done a proper TSC setup.
