### ISSUE TITLE
getLibraryPlaylists returning browseId

### ISSUE THREAD

**Issue by jtbarclay** [nickp10/youtube-music-ts-api#5]
getLibraryPlaylists is returning the browseId and not the playlistId, they appear to be nearly identical strings except my browseId's have 'VL' prepended to them.

**Comment by nickp10** [comment]
Some endpoints requires the VL and some endpoints require it without. This library will properly append the VL or trim the VL depending on the needs of each endpoint. Closing as not an issue since both representations of the ID can correctly identify the playlist.
